name: Deployment execrise
on: push
jobs:
 deploy:
  runs-on: ubuntu-22.04 
  steps:
   - name: Get code
     uses: actions/checkout@v4
   - name: Deploy the code
     run: echo "the code is deployed"
